version: '3.3'

services:
   wordpress:
     image: mcr.microsoft.com/azuredocs/multicontainerwordpress
     ports:
       - "8000:80"
     restart: always

   ssh:
     image: linkul meu
     ports: 
     -"2222:2222"
     restart: always
